### ISSUE TITLE
All frames fail to load, deleting themselves [NSaF 2]

### ISSUE THREAD

**Issue by r00ph** [CTFAK/CTFAK2.0#57]
Decompiling NSaF 2 with CTFAK.Cli went fine until the MFA only took half the EXE's space. I used no parametres.
[Latest.log](https://github.com/CTFAK/CTFAK2.0/files/12043861/Latest.log)
The game: https://drive.google.com/file/d/1_rq02CQczbcQhNG6I96-Agh73hvq8Jhz

**Comment by AITYunivers** [comment]
![image](https://github.com/CTFAK/CTFAK2.0/assets/92553545/bf49d4fc-62ef-454f-97f7-cc6f58d33f04)
Decompiles fine. Your issue is that you don't have the extensions downloaded. They're on the top of Latest.log and Clickteam tells you what they are if you refuse to delete a frame.

TL;DR Not a CTFAK issue, user-error.
